# Moonwalk
[info]
head = 1
body = 4
tail = 2

# head
[[step]]
mode = 3
gait_id = 3
contact = 15
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
ctrl_point = [ 0.0, 0.0, 0.0,]
foot_pose = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 0.0, 0.0,]
value = 0
duration = 500

# body
[[step]]
mode = 11
gait_id = 110
contact = 10
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 10.0, 10.0, 10.0, 50.0, 50.0, 10.0,]
ctrl_point = [ 0.035, 0.0, 0.4,]
foot_pose = [ 0.035, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 10050.0, 50010.0,]
value = 0
duration = 300

[[step]]
mode = 11
gait_id = 110
contact = 10
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 10.0, 10.0, 10.0, 50.0, 50.0, 10.0,]
ctrl_point = [ 0.035, 0.0, 0.4,]
foot_pose = [ 0.035, 0.0, -0.035, 0.0, -0.035, 0.0,]
step_height = [ 10050.0, 50010.0,]
value = 0
duration = 240

[[step]]
mode = 11
gait_id = 110
contact = 10
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 10.0, 10.0, 10.0, 50.0, 50.0, 10.0,]
ctrl_point = [ 0.0, 0.0, 0.4,]
foot_pose = [ 0.0, 0.0, 0.035, 0.0, 0.035, 0.0,]
step_height = [ 50010.0, 10050.0,]
value = 0
duration = 300

[[step]]
mode = 11
gait_id = 110
contact = 10
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 10.0, 10.0, 10.0, 50.0, 50.0, 10.0,]
ctrl_point = [ -0.035, 0.0, 0.4,]
foot_pose = [ -0.035, 0.0, 0.035, 0.0, 0.035, 0.0,]
step_height = [ 50010.0, 10050.0,]
value = 0
duration = 240

# tail
[[step]]
mode = 11
gait_id = 31
contact = 0
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
ctrl_point = [ 0.0, 0.0, 0.0,]
foot_pose = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 0.0, 0.0,]
value = 0
duration = 1000

[[step]]
mode = 0
gait_id = 0
contact = 0
life_count = 0
vel_des = [ 0.0, 0.0, 0.0,]
rpy_des = [ 0.0, 0.0, 0.0,]
pos_des = [ 0.0, 0.0, 0.0,]
acc_des = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
ctrl_point = [ 0.0, 0.0, 0.0,]
foot_pose = [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,]
step_height = [ 0.0, 0.0,]
value = 0
duration = 1000

