# Moonwalk
[info]
head = 0
body = 8
tail = 1

# head

# body
[[section]]
contact  = [1, 1, 1, 1]
duration = 8

[[section]]
contact  = [0, 0, 0, 0]
duration = 2

[[section]]
contact  = [0, 1, 1, 0]
duration = 6

[[section]]
contact  = [0, 0, 0, 0]
duration = 2

[[section]]
contact  = [1, 1, 1, 1]
duration = 8

[[section]]
contact  = [0, 0, 0, 0]
duration = 2

[[section]]
contact  = [1, 0, 0, 1]
duration = 6

[[section]]
contact  = [0, 0, 0, 0]
duration = 2

# tail
[[section]]
contact  = [1, 1, 1, 1]
duration = 8